[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gymlib"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
py-modules = ["gymlib"]