name: CI for Unit Tests

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      run: python scripts/run_unittests.py
