name: CI for Unit Tests

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    # We could choose to set up dependencies manually in the GHA runner.
    #
    # However, I think it's better to do them in the GHA itself so that
    # we're testing our dependency installation step in addition to our
    # actual code.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: ./dependency/install_dependencies.sh

    - name: Run unit tests
      run: python scripts/run_unittests.py
